import { useEffect, useState } from 'react';

export default function Warning() {
  const [data, setData] = useState({ url: '', risk: 0 });

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    setData({
      url: params.get('url') || '',
      risk: Number(params.get('risk')) || 0,
    });
  }, []);

  function goBack() {
    if (window.history.length > 1) {
      window.history.back();
    } else {
      window.close();
    }
  }

  function proceedAnyway() {
    if (!data.url) return;
    const confirmed = window.confirm(
      'CyberLang strongly recommends against visiting this site. ' +
      'Are you sure you want to proceed?'
    );
    /*if (confirmed) {
      window.location.replace(data.url);
    }*/
   if (!confirmed) return;

   chrome.runtime.sendMessage(
    { type: 'ALLOW_ONCE', url: data.url },
    () => {
      // Wait for the worker to acknowledge before navigating
      window.location.replace(data.url);
    }
  );
  }

  return (
    <main
      style={{
        maxWidth: 640,
        margin: '0 auto',
        padding: '4rem 2rem',
      }}
    >
      <div style={{ fontSize: '4rem', lineHeight: 1 }}>⚠️</div>
      <h1 style={{ fontSize: '2rem', margin: '1rem 0 0.5rem' }}>
        Potentially Dangerous Site
      </h1>
      <p style={{ color: '#7f1d1d', fontSize: '1.1rem' }}>
        CyberLang flagged this URL as{' '}
        <strong>{data.risk}% likely to be phishing</strong>.
      </p>

      <div
        style={{
          background: '#fff',
          border: '1px solid #fecaca',
          borderRadius: 8,
          padding: '1rem',
          margin: '1.5rem 0',
          fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
          fontSize: '0.85rem',
          wordBreak: 'break-all',
        }}
      >
        {data.url || '(no URL)'}
      </div>

      <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
        <button
          onClick={goBack}
          style={{
            background: '#dc2626',
            color: '#fff',
            border: 'none',
            borderRadius: 6,
            padding: '0.75rem 1.5rem',
            fontSize: '1rem',
            fontWeight: 600,
            cursor: 'pointer',
          }}
        >
          ← Go back to safety
        </button>
        
        {
        <button
          onClick={proceedAnyway}
          style={{
            background: 'transparent',
            color: '#6b7280',
            border: '1px solid #d1d5db',
            borderRadius: 6,
            padding: '0.75rem 1.5rem',
            fontSize: '0.95rem',
            cursor: 'pointer',
          }}
        >
          Proceed anyway
        </button>
        }
      </div>

      <p style={{ marginTop: '2rem', fontSize: '0.85rem', color: '#6b7280' }}>
        This warning was generated by the CyberLang Scanner extension. If you
        believe this is a mistake, you may proceed.
      </p>
    </main>
  );
}